server:
  shutdown: graceful

spring:
  application:
    name: sendy
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:sendy-api-local-group}
      auto-offset-reset: ${SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET:earliest}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
      session_factory:
        interceptor: com.sendy.support.util.LogUtilInterceptor
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sendy?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: sendy_master
    password: sendy_master
  mail:
    host: smtp.gmail.com
    port: 587
    username: sendy.smtp.test@gmail.com
    password: pmdfdbayumogvcea
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
      auth-code-expiration-millis: 600,000   # 10 * 60 * 1000 == 10분
# 추후 Secrets Manager 등으로 이관
aes256:
  key: d2f3de5ce2bef6aad4c2b01e2bffdcd6

springdoc:
  override-with-generic-response: false
  packages-to-scan: com
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: alpha

jwt:
  secret-key: DYS6feNXKYnsLOebpSU0Ljm05bgit9j3sc3YYoBYh2E=
  access-token-expire-time: 300
  refresh-token-expire-time: 7200
logging:
  level:
    com.sendy: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
  file:
    name: ./logs
